### ISSUE TITLE
Can't build with go1.4

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-agent#11]
```
$ ./bin/build
Currently using go version go1.4, must be using go1.3.3
```

**Comment by cppforlife** [comment]
Interestingly enough we had stability problems with previous versions of go so we locked it down to 1.3.3.  Might make sense to unlock bump that to 1.4. Do you need 1.4 for a particular reason?

**Comment by drnic** [comment]
I guess I can uninstall 1.4 and install 1.3.3. Not sure what pros I get from 1.4 for local dev.

**Comment by dhilipkumars** [comment]
Hi Dmitriy,

Im new to CF. I just bumped in this issue and was curious. I tried commenting the condition that restricts build to 1.3.3, 

#if [ $goversion != "go1.3.3" ]
#then
  #echo "Currently using go version $goversion, must be using go1.3.3"
  #exit 1
#fi

it seems to build without any problem.  Any idea what stability problems were faced previously? i could look for them and test it.

Also could we change the condition to "1.3.3 and upwards" ?
 
Dhilip

**Comment by cppforlife** [comment]
@dhilipkumars even before we locked it down, the code compiled just fine. we were testing the agent on of our environments and for some reason golang was stuck on a time.Sleep call. we recompiled with 1.3.3 and that fixed the problem consistently. feel free to file a PR to bump it if there is a specific problem with 1.3.3.

**Comment by dhilipkumars** [comment]
Hi 
Apologies for the delay in responding.  I had gotten lost setting up, deploying and understanding CF. :-).    

There is no specific problem with 1.3.3 but just thought its always better to get go programs built on the latest version.  As you may already know 1.4 has some 'gc' and goroutine stack improvements. 

Im still interested to work on it.  if you remember what was the problematic go version that made programs hang in time.Sleep and any test case you could think of?  

Regards,
Dhilip

**Comment by cppforlife** [comment]
We have relaxed golang check.
