### ISSUE TITLE
/tmp is not cleaned up during VM reboot

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#110]
Due to the design change in [this commit](https://github.com/cloudfoundry/bosh-agent/commit/d466f198aa9d3f2c7269946d9798e1c8535cc2aa#diff-bc13c7242dfb8351e889278de03af265 ), the root_tmp dir is created with "mkdir -p", so if the dir root_tmp already exists, it will not be recreated, as a result, the /tmp is not cleaned up during VM reboot. Due to this change, our DEA (CF v235) can't work properly after VM reboot, since /tmp/warden dir is not removed. We know that this problem has already been fixed from CF release side, but I wonder if it's a right behavior to not clean up /tmp after VM reboot. Thanks.

**Comment by cppforlife** [comment]
@mattcui i think it would be nice to clean up tmp though i dont think anyone should expect that /tmp is cleared after reboot. on some distributions (centos i think) /tmp isnt cleared.

**Comment by mattcui** [comment]
@cppforlife So you agree to **recreate** root_tmp at the following line code, right? If so, we will submit a PR to address it.

https://github.com/cloudfoundry/bosh-agent/blob/d466f198aa9d3f2c7269946d9798e1c8535cc2aa/platform/linux_platform.go#L702

**Comment by maximilien** [comment]
@mattcui closing this for now per our discussion. let's reopen if we find other software caring about this problem.
