### ISSUE TITLE
/var/vcap/store should not have 5% root reservation

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh-agent#112]
Currently all filesystems are created with the default 5% disk space reservation for privileged processes. While this make sense for root filesystems, it's [hard to justify](https://github.com/cloudfoundry/bosh-agent/issues/112) for volumes that are normally only written to by non-root users (vcap), especially since it's not uncommon (at least in our experience) to have very large volumes (and, therefore, quite big amounts of unusable disk space)

I think it should be safe to use `-m 0` on /var/vcap/store ~and /var/vcap/data~, but if that's deemed too risky (why?) I would at least suggest lowering the reservation to some smaller value.

**Comment by cppforlife** [comment]
@CAFxX i think it makes to be removed for persistent disk. for ephemeral storage it becomes a bit interesting since we have /var/vcap/data/root_log (bind mount from /var/log) placed there and it's written by auditd and rsyslog. not sure if they would be affected in a negative way. wdyt?

**Comment by CAFxX** [comment]
@cppforlife right, I forgot about that. Then yes, just /var/vcap/store.
