### ISSUE TITLE
VM swap size should be configurable

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/bosh-agent#115]
Currently, bosh hard-codes the size of a VM swap partition to be equal to the size of RAM or half the ephemeral disk:

https://github.com/cloudfoundry/bosh-agent/blob/255.x/platform/linux_platform.go#L997-L1014

For large amounts of memory with relatively small ephemeral disks this is a problem.
In my case I have 32G RAM with a 100G ephemeral disk. With all other overhead this cuts my ephemeral disk down to about 65G which is too low for my use cases. Also: Who needs 32G swap?

So my suggestion is to introduce a parameter for resource pools that allows CPIs to set the swap size just like memory. It would also be nice to set the swappiness of the kernel as for high-performance workloads it is generally undesired to swap at all.

**Comment by cppforlife** [comment]
@domdom82 we just recently finished up: https://www.pivotaltracker.com/story/show/133705685. it hasnt been published yet though. next major stemcell will include it.

**Comment by domdom82** [comment]
Sounds great! Thanks.
