### ISSUE TITLE
Timed out sending 'list_disk' because bosh-agent uses cached outdated settings.json

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/bosh-agent#120]
Issue Logs:
```
  Started updating instance database_z1 > database_z1/5101a816-47e5-48a4-966f-3afc6be350b8 (0) (canary). Failed: Timed out sending 'list_disk' to
cfc2345b-c38e-443c-8b29-db8d73ed1791 after 45 seconds (00:11:09)

Error 450002: Timed out sending 'list_disk' to cfc2345b-c38e-443c-8b29-db8d73ed1791 after 45 seconds
```

Reproduce steps on Azure:
1.  Resize the persistent data disk of database_z1 (VM size: F1)
2. Update the deployment
3.  It will fail because F1 only allows to attach 2 data disks(LUN 0: Ephemeral disk; LUN 1:  Current data disk)
4. Change the VM size of database_z1 to F2
5. Update the deployment
6.  It will fail with above error. 

Root cause:
In step 5,
1. bosh called Azure CPI to attach the new disk with new size
1. bosh send `list_disk` to bosh-agent inside database_z1
1. bosh send `mount_disk` to bosh-agent inside database_z1
1. bosh-agent fetched new settings from bosh-registry and wrote it to `/var/vcap/bosh/settings.json`
1. bosh send `migrate_disk` to bosh-agent inside database_z1
1. bosh called Azure CPI to detach the old disk
1. bosh send `list_disk` to bosh-agent inside database_z1
1. bosh-agent *did not* fetch new settings from bosh-registry but [got settings](https://github.com/cloudfoundry/bosh-agent/blob/920dd6fc99a5fb8860c215a27e343732c8d66ba8/agent/action/list_disk.go#L42) from `/var/vcap/bosh/settings.json`. There are two data disks (Exclude ephemeral data disk) in the settings so that it failed with timeout.

**Comment by cppforlife** [comment]
@AbelHu quickly glancing at disk_manager code i dont see where we call list_disk after migrate_disk.

**Comment by AbelHu** [comment]
@cppforlife I added some logs in disk_manager.rb for debugging and found that the issue was caused by [Line 168](https://github.com/cloudfoundry/bosh/blob/v260.5/bosh-director/lib/bosh/director/disk_manager.rb#L168).

```
      agent_client(instance_model).list_disk
```

[Line 60](https://github.com/cloudfoundry/bosh/blob/v260.5/bosh-director/lib/bosh/director/disk_manager.rb#L60) was called in Line [51-62](https://github.com/cloudfoundry/bosh/blob/v260.5/bosh-director/lib/bosh/director/disk_manager.rb#L51-L62):
```
        if old_disk_model
          detach_disk(old_disk_model)

          @orphan_disk_manager.orphan_disk(old_disk_model)
        end
      end

      inactive_disks = Models::PersistentDisk.where(active: false, instance: instance_model)
      inactive_disks.each do |disk|
        detach_disk(disk)
        @orphan_disk_manager.orphan_disk(disk)
      end
```

**Comment by cppforlife** [comment]
I think I understand now the problem (relates to first deploy failing with F1). Story: https://www.pivotaltracker.com/story/show/140726061

**Comment by AbelHu** [comment]
@cppforlife The timeout for scsiLunPathResolver is 50000 ms but the timeout for list_disk is 45 seconds. So if an out-dated cache  settings.json is used, this issue always occurs.

[provider.go#L106](https://github.com/cloudfoundry/bosh-agent/blob/9b556bad2e02ea1bd91745205da1266fe44279ad/platform/provider.go#L106)
```
scsiLunPathResolver := devicepathresolver.NewSCSILunDevicePathResolver(50000*time.Millisecond, fs, logger)
```

**Comment by pdelagrave** [comment]
Hi @AbelHu 
We've seen the `list_disk` error but also this `mount_disk` error that seems very similar. Can you confirm whether the proposed fix would solve this other problem?

Thanks!

[task55.log.txt](https://github.com/cloudfoundry/bosh-agent/files/811804/task55.log.txt)

```
  Started creating missing vms
  Started creating missing vms > cf-redis-broker/c969ef24-931d-4916-9066-64dc88eb71a7 (0)
  Started creating missing vms > dedicated-node/a3db4259-1f74-46d8-aa94-454f7d14132b (0)
  Started creating missing vms > dedicated-node/2e3a6579-c30c-4922-a2ae-7cf501e45589 (4)
  Started creating missing vms > dedicated-node/554d2805-71ad-4e8d-a96d-72063bf7f65c (2)
  Started creating missing vms > dedicated-node/ef4de4d5-502b-43c9-963c-74c402982357 (3)
  Started creating missing vms > dedicated-node/fe66f173-dd54-441b-a57b-dbd982e990c0 (1)
     Done creating missing vms > dedicated-node/ef4de4d5-502b-43c9-963c-74c402982357 (3) (00:01:44)
     Done creating missing vms > dedicated-node/a3db4259-1f74-46d8-aa94-454f7d14132b (0) (00:01:47)
     Done creating missing vms > cf-redis-broker/c969ef24-931d-4916-9066-64dc88eb71a7 (0) (00:02:06)
     Done creating missing vms > dedicated-node/fe66f173-dd54-441b-a57b-dbd982e990c0 (1) (00:02:09)
     Done creating missing vms > dedicated-node/554d2805-71ad-4e8d-a96d-72063bf7f65c (2) (00:02:12)
     Done creating missing vms > dedicated-node/2e3a6579-c30c-4922-a2ae-7cf501e45589 (4) (00:02:35)
     Done creating missing vms (00:02:35)

  Started updating instance cf-redis-broker > cf-redis-broker/c969ef24-931d-4916-9066-64dc88eb71a7 (0) (canary). Done (00:01:51)
  Started updating instance dedicated-node
  Started updating instance dedicated-node > dedicated-node/a3db4259-1f74-46d8-aa94-454f7d14132b (0) (canary). Failed: Timed out sending 'mount_disk' to 9ab1b5ae-39bf-437e-88e2-83288c04a2c5 after 45 seconds (00:14:46)

Error 450002: Timed out sending 'mount_disk' to 9ab1b5ae-39bf-437e-88e2-83288c04a2c5 after 45 seconds

Task 55 error
```

**Comment by AbelHu** [comment]
@pdelagrave From the task log, I cannot find any useful information so I do not know whether they are caused by the same reason.. I suggest you to login to the failed VM and check bosh-agent's log. The path is `/var/vcap/bosh/log/`.

**Comment by AbelHu** [comment]
It was fixed in latest stemcells.
