### ISSUE TITLE
bosh agent cert is expired

### ISSUE THREAD

**Issue by leejian0612** [cloudfoundry/bosh-agent#128]
HI, all,
the agent.cert is expired from 2016.12.1, Can someone help to update it?
root@1ab957b6-289c-405b-565b-ee6edc242a8a:/var/vcap/bosh# openssl x509 -in /var/vcap/bosh/agent.cert -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=Pivotal, CN=localhost
        Validity
            **Not Before: Dec  1 22:11:32 2013 GMT
            Not After : Dec  1 22:11:32 2016 GMT**
        Subject: C=US, O=Pivotal, CN=localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)

  
https://github.com/cloudfoundry/bosh-agent/blob/master/httpsdispatcher/agent.cert

**Comment by cppforlife** [comment]
@leejian0612 upcoming stemcell will include configuration item that allows you to specify custom cert through agent configuration.

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/145462855

**Comment by cppforlife** [comment]
@leejian0612 shoudl be able to override cert with whatever cert you need via env.bosh.mbus.cert option. https://github.com/cloudfoundry/bosh-deployment/blob/master/bosh.yml#L10-L17
