### ISSUE TITLE
Drain/stop scripts should be run on OS shutdown

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh-agent#134]
In case the OS is requested to shutdown (e.g. by the underlying IaaS) it would be appropriate for the drain scripts and monit stop to be called to at least try to limit impact due to the VM shutting down.

While this is unlikely to be useful on normal public cloud deployments, it is a scenario that happens in practice on prem. It may also be useful for e.g. AWS spot instances.

**Comment by cppforlife** [comment]
@CAFxX what's interesting about this scenario is that it may be dangerous to run drain script on shutdown given that it does not have any control over timing. may be vm is only rebooting and it should not drain, etc.? should this be done via an additional hook? which jobs did you have in mind that would benefit from such draining? concourse?

**Comment by CAFxX** [comment]
> which jobs did you have in mind that would benefit from such draining?

Any job that needs some time to cleanly detach from a load balancer to avoid service impact.
