### ISSUE TITLE
Ephemeral disk is re-partitioned due to memory size change after Xen server upgrade

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#138]
We observed that the memory size change after Xen server upgrade (like from 6.x to 7.x) is usually more than 20M, which caused the ephemeral disk was re-patitioned and formatted after Xen upgrade (VMs were all rebooted), seems that 100M is a safe size for such case, is it possible to extend the size to 100M in agent code below? Thanks.

https://github.com/cloudfoundry/bosh-agent/blob/master/platform/disk/parted_partitioner.go#L90
https://github.com/cloudfoundry/bosh-agent/blob/master/platform/disk/sfdisk_partitioner.go#L150

/cc @maximilien @cppforlife

**Comment by cppforlife** [comment]
Sound reasonable, we can expand to 100MB.

Story: https://www.pivotaltracker.com/story/show/151270696

**Comment by dpb587-pivotal** [comment]
Closing - released in [3541.2](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/releases/tag/stable-3541.2) stemcell.

**Comment by maximilien** [comment]
Thank you @dpb587 and @cppforlife 

We'll test this out soon as we roll out latest stemcell.

Best.
