### ISSUE TITLE
Happen a `no interface configured with that name` when virtual net interface pass Validate

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-agent#144]
When the VM created by cpi setup, we could get 3 interfaces in `/sys/class/net` (`ls /sys/class/net`: lo, eth0, eth1). Agent got its settings which is listed below and then setup networks:

```
{
  "networks": {
    "default": {
      "type": "manual",
      "ip": "10.112.166.136",
      "netmask": "255.255.255.192",
      "gateway": "",
      "resolved": false,
      "use_dhcp": false,
      "default": null,
      "dns": [
        "8.8.8.8"
      ],
      "mac": "",
      "preconfigured": false,
      "alias": "eth0:0"
    },
    "dynamic": {
      "type": "dynamic",
      "ip": "169.50.68.75",
      "netmask": "255.255.255.224",
      "gateway": "169.50.68.65",
      "resolved": false,
      "use_dhcp": false,
      "default": [
        "gateway",
        "dns"
      ],
      "dns": [
        "8.8.8.8",
        "10.0.80.11",
        "10.0.80.12"
      ],
      "mac": "06:f2:b7:01:a7:ca",
      "preconfigured": false,
      "alias": "eth1"
    },
    "dynamic_1": {
      "type": "dynamic",
      "ip": "10.112.39.113",
      "netmask": "255.255.255.128",
      "gateway": "",
      "resolved": false,
      "use_dhcp": false,
      "default": null,
      "dns": [
        "8.8.8.8",
        "10.0.80.11",
        "10.0.80.12"
      ],
      "mac": "06:b7:d5:35:6b:7a",
      "preconfigured": false,
      "alias": "eth0",
      "routes": [
        {
          "Destination": "10.0.0.0",
          "Gateway": "10.112.39.1",
          "NetMask": "255.0.0.0"
        },
        {
          "Destination": "161.26.0.0",
          "Gateway": "10.112.39.1",
          "NetMask": "255.255.0.0"
        }
      ]
    }
  }
}
```
Two dynamic networks are provided by the IaaS, The manual network is a virtual network interface based on the original net interface(dynamic_1). These configurations could write to `/etc/network/interfaces` and be applied. 

But when invoke `net.interfaceAddressesValidator.Validate(staticAddresses)` in [code#1](https://github.com/cloudfoundry/bosh-agent/blob/master/platform/net/ubuntu_net_manager.go#L176), a `no interface configured with that name` error with `eth0:0` occured because systemInterfaceAddresses list didn't have the virtual interface.

```
2017-10-12_12:39:11.89281 [main] 2017/10/12 12:39:11 ERROR - App setup Running bootstrap: Setting up networking: Validating static network configuration: Validating network interface 'eth0:0' IP addresses, no interface configured with that name: <nil cause>
```

The temporary solution is to exclude virtual IP from validation as I could think around. 
Could you please help us to tell some useful advise or add some mechanism for dealing with VIF-related problems in the bosh-agent.

Thank you, guys!

**Comment by voelzmo** [comment]
@EdwardStudy which IaaS are you running on? The CPIs currently have some limitations with regards to multiple networks. Please see table http://bosh.io/docs/networks.html#cpi-limitations for reference.

**Comment by EdwardStudy** [comment]
@voelzmo we are developing new CPI based on Softlayer. The dynamic networks can be assigned two physical interfaces(the `eth0` is Softlayer's private network, the `eth1` is Softlayer's public network) and the manual network is a virtual interface based on eth0 defined by network cloud_properties(like below manifest segment).

```
networks:
- name: default
  subnets:
  - cloud_properties:
      vlanIds:
      - 524954
    dns:
    - 8.8.8.8
    gateway: 10.112.166.129
    range: 10.112.166.128/26
    static:
    - 10.112.166.134
  type: manual
```

The networks were fine and bosh-cli could ping 3 ips successfully and deploy applications. But agent failed to validate interface addresses because of the virtual net interface. The detailed reason is that the virtual network interface is based on an original net interface. 

So, should the bosh agent take the matter of the virtual network interfaces into account?

**Comment by dpb587-pivotal** [comment]
@EdwardStudy, you mention you're working on a new SoftLayer CPI, and it looks like you've run into [cloudfoundry/bosh-softlayer-cpi-release](https://github.com/cloudfoundry/bosh-softlayer-cpi-release) before, but I was wondering if this is an issue when using the existing SoftLayer CPI?

**Comment by EdwardStudy** [comment]
@dpb587-pivotal In the existing SoftLayer CPI, network is configured by cpi. So there is no such problem in the existing SoftLayer CPI. And we met this issue because we want to use bosh-agent way to setup network in the future.

Thank you.

**Comment by EdwardStudy** [comment]
And I want to know if we occured same problems  in other IaaS. 
How about to filter VIFs before invoke `net.interfaceAddressesValidator.Validate(staticAddresses)` ?

**Comment by cppforlife** [comment]
@EdwardStudy is this related to not implementing "aliasing". ie multiple networks actually reference to the same nic?

**Comment by EdwardStudy** [comment]
Yes. It is about VIFs.

**Comment by cppforlife** [comment]
i think we shoudl account for aliasing in validation portion.

**Comment by EdwardStudy** [comment]
@cppforlife Hi. Did you mean that use based interface to validate the virtual interface? Or any method else?
