### ISSUE TITLE
agent stops without apparent cause

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-agent#145]
I am having issues with a bosh-lite deployed to a vsphere bosh environment (that is, it was created with `bosh deploy` using `-o misc/bosh-dev.yml`). I'm trying to debug it. 

I redeployed the VM and tailed the `/var/vcap/bosh/log/current` and eventually it just stops with this last line:

```
2017-10-29_22:38:19.80190 [main] 2017/10/29 22:38:19 ERROR - Agent exited with error: received signal (terminated): stopping now
```

There is nothing preceding this line that indicates why the agent stopped. The agent never restarts (shouldn't the local process monitoring software restart the agent?)

Eventually the parent BOSH gets cranky that the `bosh-agent` stopped (and never restarted) and resurrects the bosh-lite vm (which means it stops being useful for 7 minutes).

```
$ bosh tasks --all
Using environment 'https://10.58.111.4:25555' as user 'admin' (openid, bosh.admin)

ID       State       Started At                    Last Activity At              User  Deployment    Description   Result
4567676  processing  Sun Oct 29 23:05:07 UTC 2017  Sun Oct 29 23:05:07 UTC 2017  hm    bosh-lite-10  scan and fix  -

1 tasks

$ bosh task 4567676
Task 4567676 | 23:06:15 | Applying problem resolutions: VM for 'bosh/83887585-6b46-468f-b913-26434a36ce23 (0)' with cloud ID 'vm-9f994659-4a27-4e43-a177-358c1c4f1b98' is not responding. (unresponsive_agent 2308): Recreate VM and wait for processes to start

Task 4567676 Started  Sun Oct 29 23:05:07 UTC 2017
Task 4567676 Finished Sun Oct 29 23:12:11 UTC 2017
Task 4567676 Duration 00:07:04
```

There is about 7:20 between `scan and fix` task below, and given that it takes 7:04 minutes to resurrect the VM, the agent is surviving only 15 seconds after it finishes deploying all the BOSH/bosh-lite jobs.

```
$ bosh tasks --recent -a | grep done | grep scan
4567689 done      	Sun Oct 29 23:12:28 UTC 2017	Sun Oct 29 23:12:34 UTC 2017	hm   	bosh-lite-10	scan and fix                           	scan and fix complete
4567676 done      	Sun Oct 29 23:05:07 UTC 2017	Sun Oct 29 23:12:11 UTC 2017	hm   	bosh-lite-10	scan and fix                           	scan and fix complete
4567660 done      	Sun Oct 29 22:56:07 UTC 2017	Sun Oct 29 23:02:39 UTC 2017	hm   	bosh-lite-10	scan and fix                           	scan and fix complete
```

How can I debug this issue? It's very consistent - even though using fresh vms each time. But yet I'm just using HEAD from bosh-deployment and this combination of operator files:

```
bosh -n deploy bosh-deployment/bosh.yml \
      -o bosh-deployment/bosh-lite.yml \
      -o bosh-deployment/bosh-lite-runc.yml \
      -o bosh-deployment/misc/bosh-dev.yml \
      -o bosh-deployment/jumpbox-user.yml \
      -o bosh-deployment/uaa.yml \
      -o bosh-deployment/credhub.yml \
      -o bosh/deploy-ops.yml \
      -o bosh/$NAME/deploy-ops.yml \
      -l bosh/$NAME/vars.yml \
      --vars-store bosh-credentials/$NAME.yml
```

dmesg output https://gist.github.com/drnic/a8b60a7276954e2fcfc749d8a16393c7

Update: I've disabled resurrection, and the agent dies again, I've manually restarted the agent. I am waiting patiently for the agent to die again.

Update: I'm also trying `bosh cloud-check` (after turning off resurrector) with "recreate vm without waiting for processes". Agent doesn't seem to to die after `bosh cloud-check` recreation.

**Comment by dpb587-pivotal** [comment]
By default, bosh-lite will disable the agent since they're typically used as throwaway environments. The [bosh-lite.yml](https://github.com/cloudfoundry/bosh-deployment/blob/61c34a427c56b878cc972dcac09d4aa62b6cd529/bosh-lite.yml#L37-L41) ops file configures the `disable_agent` job from `os-conf` release. If you're managing these with another directory and not create-env, you may want to remove it.

**Comment by drnic** [comment]
@dpb587-pivotal thanks very much for pointing that out.

Does this mean that I'm the only one running bosh-lites for CI? Or am I the only one using `bosh deploy` to run bosh-lites (so they are resurrected, etc)? How is everyone else doing CI with BOSH - just provisioning lots of VMs and paying the cost to AWS/Google?

**Comment by drnic** [comment]
Can we add the following to `misc/bosh-dev.yml`?

```
- type: delete
  path: /instance_groups/name=bosh/jobs/name=disable_agent
```

**Comment by dpb587-pivotal** [comment]
Sounds like a good idea to me. Perhaps `name=disable_agent?` in case it's already removed.
