### ISSUE TITLE
Can't use File source without registry.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-agent#15]
You can set the agent to read settings from file using following config options:
```yaml
{
  ...
  "Infrastructure": {
    "Settings": {
      "Sources": [
        {
          "Type": "File",
          "MetaDataPath": "/home/vcap/metadata",
          "UserDataPath": "/home/vcap/userdata",
          "SettingsPath": "/home/vcap/settings"
        }
      ]
    }
  }
}
```
Without `UseRegistry` option you'll get [this error](https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/settings_source_factory.go#L156): `File source is not supported without registry`.

Could you tell if there is any actual reason to restrict to read settings from file if you don't use registry?

**Comment by bosh-ci-push-pull** [comment]
Not technical reason, we just have not implemented that in bosh-agent:
https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/settings_source_factory.go#L156

Our plan is to actually remove registry completely so at some point we will
implement this option.

**Comment by allomov** [comment]
May I create PR for this?

**Comment by mariash** [comment]
Hi @allomov, 

If you want to inject the file with settings you can use the file based registry. The settings source in agent.json represents the metadata source, which in case of file is file based metadata/userdata source. This is to be consistent with other source types.

```
{
  ...
  "Infrastructure": {
    "Settings": {
      "Sources": [
        {
          "Type": "File",
          "MetaDataPath": "/home/vcap/metadata",
          "UserDataPath": "/home/vcap/userdata"
        }
      ]
    }
  }
}
```
In your userdata file just set registry endpoint to the file path.
```
{
  "server": {
    "name": "instance-id"
  },
  "registry": {
    "endpoint": "/home/vcap/settings.json"
  }
}
```

**Comment by allomov** [comment]
Thank you, @mariash, for answer. It may help.

But don't you think that having `SettingsPath` [option](https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/settings_source_factory.go#L53) in file source settings can cause a confusion? Could you add more details about consistency with other source types?

Because from my view, it is easier to use `SettingsPath` option to read settings from file, rather than passing registry endpoint through userdata to read the settings from the same file. Another point for using `SettingsPath` in file source without registry is that registry is going to be deprecated. I guess this changes should be made sometime. What do you think?

**Comment by cppforlife** [comment]
@allomov We'll take a PR for making FileSettingsSource without registry.
