### ISSUE TITLE
Why do you return empty string as a name in file metadata source?

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-agent#16]
[In this code](https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/file_metadata_service.go#L67) empty string is return as a server name. I thought that file metadata source works much a like as another metadata services. So if you set `Name` option, then agent can get it from any type of source. Think that this should be changed.

**Comment by maximilien** [comment]
If I recall correctly in the `FileMetaData` the `ServerName` does not make sense but we need to implement so that the interface method requirement is satisfied. A better question could be why keep that method in that interface?

**Comment by allomov** [comment]
I guess the reason is that BOSH writes VM name as a metadata (link to [sources](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli_plugin_micro/lib/bosh/deployer/instance_manager.rb#L124)). 

In case with OpenStack CPI bosh-agent reads VM name from metadata and then asks registry about initial settings using the name as an ID (link to [sources](https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/http_registry.go#L42)).

**Comment by allomov** [comment]
https://github.com/cloudfoundry/bosh-agent/pull/39 should fix this problem
