### ISSUE TITLE
noatime for /var/vcap/store (Optimizing Disk I/O for databases)

### ISSUE THREAD

**Issue by GETandSELECT** [cloudfoundry/bosh-agent#166]
Hey

is it possible to add on option for specify `noatime` or `nodiratime` for `/var/vcap/store`? MongoDB and MySQL recommend that for [performance improvement](https://dev.mysql.com/doc/refman/5.7/en/disk-issues.html):

> Optimizing Disk I/O
> 
>  You can also set the parameters for the file system that the database uses:
> 
> If you do not need to know when files were last accessed (which is not really useful on a database server), you can mount your file systems with the -o noatime option. That skips updates to the last access time in inodes on the file system, which avoids some disk seeks.

thanks

cheers GETandSELECT

**Comment by cppforlife** [comment]
@GETandSELECT just updated [1] with `persistent_disk_mount_options` option for instance groups.

[1] https://github.com/cloudfoundry/docs-bosh/blob/master/content/manifest-v2.md#instance-groups-block--instance-groups-

**Comment by GETandSELECT** [comment]
thanks @cppforlife for documentation update.
