### ISSUE TITLE
configure Bosh Agent start on fixed port

### ISSUE THREAD

**Issue by challa** [cloudfoundry/bosh-agent#167]
This it not a bug but i need clarification

bosh agent starts on ephimeral port  in our system the range is (32768 to 60999 )  we have another application that also start on the same range it will remember the port and on restart of server it will again start on the same port.  sometimes bosh agent collides with this application on server restart  as bosh-agent start first and all ports are free.

Bosh agent port changes one every restart.  just want to know is there a way to configure bosh agent to start on specific port. I know if its client application there is no way to specify port.  

But just wanted to check the posibility

**Comment by cppforlife** [comment]
@challa 

> bosh agent starts on ephimeral port in our system the range

bosh-agent doesnt use any ports explicitly unless it's for outbound connections which are _assigned by the kernel itself_.

> same range it will remember the port and on restart of server it will again start on the same port

that sounds pretty dangerous as kernel may have assigned this port for something else (for example, inbound ssh connection).

**Comment by cppforlife** [comment]
> I know if its client application there is no way to specify port.

ah, missed this, sounds like you already are aware of this in general.

**Comment by challa** [comment]
@cppforlife  Thanks for clarifications & quick response.
