### ISSUE TITLE
 bosh-agent assumes presence of legacy GRUB 

### ISSUE THREAD

**Issue by dmutreja** [cloudfoundry/bosh-agent#169]
The issue is seen when running [stemcell verification suite](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/tree/master/src/github.com/cloudfoundry/stemcell-acceptance-tests) against Ubuntu trusty stemcells that use GRUB2 instead of the older GRUB (a.k.a Legacy GRUB)

One of the tests that suite verifies that an agent is able to configure IPV6 for localhost. Interface https://github.com/cloudfoundry/bosh-agent/blob/ff4fa1f85a18fa6e6c9cf7b8d743a2f016adc5a1/platform/net/kernel_ipv6.go#L11 responsible for enabling that configuration assumes the stemcell is using legacy GRUB.  That is, the implementation updates "/boot/grub/grub.conf" and reboots the VM, and bails out if that configuration file is missing.

```
2018-04-17_19:34:04.75637 [main] 2018/04/17 19:34:04 ERROR - App setup Running bootstrap: Setting up IPv6: Reading grub: Opening file /boot/grub/grub.conf: open /boot/grub/grub.conf: no such file or directory
2018-04-17_19:34:04.75644 [main] 2018/04/17 19:34:04 ERROR - Agent exited with error: Running bootstrap: Setting up IPv6: Reading grub: Opening file /boot/grub/grub.conf: open /boot/grub/grub.conf: no such file or directory
```

In GRUB2, boot configuration is stored in /boot/grub/grub.cfg and not /boot/grub/grub.conf. 

Agent needs to be modified to handle VMs that use GRUB2 instead of GRUB

**Comment by cppforlife** [comment]
cc @cunnie we should check up on this for xenial stemcell as well.

**Comment by cppforlife** [comment]
@dmutreja just to double check, on oracle cloud GRUB2 is used, right?

**Comment by dmutreja** [comment]
Correct, e.g. on a vm built from our stemcell
```
bosh/0:~$ grub-install --version 
grub-install (GRUB) 2.02~beta2-9ubuntu1.14
bosh/0:~$ 
```

**Comment by manno** [comment]
We also had to add grub2 support for the openSUSE stemcell in PR #164
