### ISSUE TITLE
NTP on Windows is broken due to not running w32tm via PowerShell

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/bosh-agent#171]
We're testing stemcell 1200.18 and the NTP configuration on Windows is broken.  The configuration appears as such:

    w32tm /query /configuration
    <snip>
    NtpServer: "10.10.10.10" (Local)
    </snip>

Note the quotes included in the configuration, which is invalid.  Comparing to a previous stemcell the config looks like this:

    NtpServer: 10.10.10.10 (Local)

This appears to be caused by https://github.com/cloudfoundry/bosh-agent/commit/079c7b5afbbf867ee75fd322047b4437df8faed7.  From the logs on an older stemcell:

    [Cmd Runner] 2018/05/24 20:45:51 DEBUG - Running command: powershell w32tm /config /syncfromflags:manual /manualpeerlist:"10.10.10.10"

The 1200.18 stemcell shows this in the logs (note the missing "powershell" in the command):

    [Cmd Runner] 2018/05/24 17:10:05 DEBUG - Running command: w32tm /config /syncfromflags:manual /manualpeerlist:"10.10.10.10"

**Comment by cppforlife** [comment]
cc @mhoran

**Comment by kartiklunkad26** [comment]
Hi @amhuber yes we have identified this and fixed it. We will be releasing 1200.20 this week, that will address the issue.
