### ISSUE TITLE
unit test faced 'certificate has expired or is not yet valid' error

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-agent#193]
Hi,

I just build a customized agent from 2.117.0. Mbus/https test cases faced `Get https://user:pass@localhost:6900/healthz: x509: certificate has expired or is not yet valid` error.

**Comment by pivotal-mp** [comment]
This should be fixed on `master` as of https://github.com/cloudfoundry/bosh-agent/commit/2e46cc56fabd96a66682a15e020e87a83956e549 and on `2.117.x` as of https://github.com/cloudfoundry/bosh-agent/commit/7de8b23b066193980ce458d5adc7fff314fe8b40.

**Comment by edwardstudy** [comment]
@pivotal-mp Thanks.
