### ISSUE TITLE
Bogus certificate always installed to: `/var/vcap/bosh/agent.cert`

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/bosh-agent#197]
We've been poking around our `/var/vcap/bosh` in our quest to find out which certificates are being used where and noticed that all(?) of our bosh managed VMs include a `/var/vcap/bosh/agent.cert` which, unless we hop in a DeLorean and turn the dial back to 2016 simply won't work:

```
cat /var/vcap/bosh/agent.cert | openssl x509 -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=Pivotal, CN=localhost
        Validity
            Not Before: Dec  1 22:11:32 2013 GMT
            Not After : Dec  1 22:11:32 2016 GMT
        Subject: C=US, O=Pivotal, CN=localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ba:da:dd:82:31:d0:ee:8f:2d:c4:2c:1c:05:db:
...
```

(note also the vintage use of a SHA1 signature)

Pretty sure these are unused (since it is expired and won't work). Would it be possible to find a way to not deploy these bogus files?

**Comment by beyhan** [comment]
The bosh agent will use `/var/vcap/bosh/agent.cert` when not [mbus.cert](https://github.com/cloudfoundry/bosh-deployment/blob/13cf7e11fba28c98f81f339008d67cea4f5a95d0/bosh.yml#L21) is defined. See the agent logic [here](https://github.com/cloudfoundry/bosh-agent/blob/e5514efd7b2388ef65980f1109dd7fecf752384c/mbus/https_dispatcher.go#L79-L89). I'm not sure who is generating the `/var/vcap/bosh/agent.cert` and why it's outdated.

**Comment by aeijdenberg** [comment]
@beyhan - yes I found the code that might use it, but I also couldn't find where it came from.

So far as I can tell it is not generated - as the file appeared to be identical across more than one `bosh` installation.

**Comment by aeijdenberg** [comment]
Found it: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/stemcell_builder/stages/bosh_go_agent/assets/mbus/agent.cert

**Comment by beyhan** [comment]
@aeijdenberg the xenial stemcell `250.4+` doesn't contain the certificate any more. I think the issue can be closed? The agent will fail to start now if there is no [mbus_bootstrap_ssl ](https://github.com/cloudfoundry/bosh-deployment/blob/6bcf5669068a28087a758234d7b80e2c22fd4275/bosh.yml#L160) configured.

**Comment by aeijdenberg** [comment]
Yes, agreed, closing this out. Thanks.
