### ISSUE TITLE
PartedPartitioner doesn't return an error if parted fails to read partition table

### ISSUE THREAD

**Issue by NautiluX** [cloudfoundry/bosh-agent#214]
### Bug description

In one of our VMs on the command executed by bosh-agent [here](https://github.com/cloudfoundry/bosh-agent/blob/23b78ed80a065f8606d0244369ecd755bed8dab8/platform/disk/parted_partitioner.go#L210) fails and doesn't list the existing partitions.

Executing it on the VM gives us:

```
# parted -m /dev/xvdf print
Error: Weird block size on device descriptor: 16689 bytes is not divisible by 512.     # <--- this is printed to stderr
BYT;
/dev/xvdf:85.9GB:xvd:512:512:unknown:Xen Virtual Block Device:;
```

Stderr is not considered in agent code [here](https://github.com/cloudfoundry/bosh-agent/blob/23b78ed80a065f8606d0244369ecd755bed8dab8/platform/disk/parted_partitioner.go#L116), hence `PartedPartitioner` decides to [create a partition](https://github.com/cloudfoundry/bosh-agent/blob/23b78ed80a065f8606d0244369ecd755bed8dab8/platform/disk/parted_partitioner.go#L288), which fails with the same error:

```
Mounting persistent disk: Partitioning disk: Partitioning disk `/dev/xvdf': Creating partition using parted: Running command: 'parted -s /dev/xvdf unit B mkpart bosh-partition-0 1048576 85898297343', stdout: '', stderr: 'Error: Weird block size on device descriptor: 16689 bytes is not divisible by 512.
```

### Expected Behavior

We'd expect bosh-agent to fail when not being able to read the partition table instead of trying to partition.

### Additional Context

* This happened during the upgrade of the VM from Ubuntu Trusty to Xenial (`sfdisk` -> `parted`)
* `sfdisk` is able to read the partition table correctly
* This happened on an AWS deployed VM.

@friegger @BeckerMax @voelzmo

**Comment by aashah** [comment]
Hello,

Are there reproduction steps available for the initial failure you found?

Would be nice to see if the issue stems from a prior bosh-agent command. I'm also a little surprised the `parted` command exited 0 as well. That's something that would be helpful to look into after reproducing this.

**Comment by NautiluX** [comment]
Hi @aashah,

unfortunately I cannot provide reproduction steps. The partition table somehow got broken (at least unreadable for parted) and from the error we retrieved it looks like parted assumed it was a mac partition table.
The parted print command exits with rc 0.

**Comment by jaresty** [comment]
This request makes sense to me. I've moved it into our Pre-IPM section to discuss with the rest of the team and prioritize a fix.
