### ISSUE TITLE
[Windows] Failing process not reliably reported

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh-agent#219]
Process monitoring on windows VMs does not consistently report failing processes. 

If a job launches a powershell script that only contains `exit 1`, then in a windows deployment:
Linux behaviour (expected):
 - deployment fails
 - `bosh vms` and `bosh instances -p` will consistently report `failing`

Actual windows behaviour:
- the deployment succeeds
- `bosh vms` and `bosh instances -p` will alternately report `running` or `failing` 

Dummy release with linux and windows jobs that only `exit 1`
[winexit-release.zip](https://github.com/cloudfoundry/bosh-agent/files/3242427/winexit-release.zip)

Sample manifests for dummy release
[linexitman.txt](https://github.com/cloudfoundry/bosh-agent/files/3242432/linexitman.txt)
[winexitman.txt](https://github.com/cloudfoundry/bosh-agent/files/3242433/winexitman.txt)

**Comment by omergdn** [comment]
Has something been done in that matter?
I'm experiencing the same exact issue.
Tanzu Ops Manager + BOSH Director version: v2.10.39-build.450
VMware Tanzu Application Service version: v2.11.19
VMware Tanzu Application Service for Windows version: v2.11.11
