### ISSUE TITLE
Resizing disk with enable_cpi_resize_disk option gets error "<disk> contains a partition created by bosh. No partitioning is allowed" 

### ISSUE THREAD

**Issue by pivotal-todd-robbins** [cloudfoundry/bosh-agent#221]
Parted partioner checks added into BOSH agent in Xenial appear to be incompatible with enable_cpi_resize_disk CPI option.

Attempting to resize a disk with enable_cpi_resize_disk will fail with error:

```
L Error: Action Failed get_task: Task f42c8157-6f41-4110-4136-49d311b8f387 result: Mounting persistent disk: Partitioning disk: '/dev/vdb' contains a partition created by bosh. No partitioning is allowed. Task 42 | 15:04:40 | Error: Action Failed get_task: Task f42c8157-6f41-4110-4136-49d311b8f387 result: Mounting persistent disk: Partitioning disk: '/dev/vdb' contains a partition created by bosh. No partitioning is allowed.
```

enable_cpi_resize_disk flag previously was able to successfully resize disk in trusty though BOSH agent did not have logic to grow filesystem. Now the disk will fail attaching because agent will find partition with name "bosh-partition" when mounting the disk and fail the BOSH task.

It seems checks added in [parted_partitioner.go](https://github.com/cloudfoundry/bosh-agent/blob/e11e56fe8de33c158d2d66ae89a678e6eeaee8af/platform/disk/parted_partitioner.go) has made it so resizing disk in place via enable_cpi_resize_disk flag cannot work.

**Comment by beyhan** [comment]
Hi @pivotal-todd-robbins,

this is a known issue and here is [the story](https://www.pivotaltracker.com/story/show/159212614), which is planed for it. Issue https://github.com/cloudfoundry/bosh-agent/issues/154 is also related.

**Comment by SteveH-US** [comment]
Hi Beyhan,

Neither the story you references about growing the file system nor issue #154 is directly related to this problem.  The bosh agent code explicitly disallows resizing the partitions that it created. So, with the introduction of this restriction, neither case would occur.

**Comment by beyhan** [comment]
Yes, this restriction in bosh agent has to change for the resizing use case. This has been analyzed in https://www.pivotaltracker.com/n/projects/1456570/stories/161478343, which is referenced in the top story linked in my previous comment.

**Comment by rushs-us** [comment]
I contributed a fix for that here:
https://github.com/cloudfoundry/bosh-agent/pull/233
