### ISSUE TITLE
systemd-networkd network file doesn't work for virtual interface

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-agent#226]
After bosh agent switched from ipupdown to systemd-networkd (commit https://github.com/cloudfoundry/bosh-agent/commit/2c178e6c7f46b8964d8f97f5fc471788649b4687), the systemd-networkd network file for virtual interface ethx:y (like eth0:1) doesn't configure the interface correctly which makes the virtual interface doesn't work.

For example, we need to configure `eth0`, `eth0:1` and `eth1` for a VM. The new bosh agent generates the following network files for them:
```
# ll /etc/systemd/network
total 20
drwxr-xr-x 2 root root 4096 Nov 20 05:31 ./
drwxr-xr-x 5 root root 4096 Nov 13 02:31 ../
-rw-r--r-- 1 root root  126 Nov 20 05:31 10_eth0:1.network
-rw-r--r-- 1 root root  277 Nov 20 05:33 10_eth0.network
-rw-r--r-- 1 root root  176 Nov 20 05:31 10_eth1.network
```

```
# cat 10_eth0:1.network
# Generated by bosh-agent
[Match]
Name=eth0:1

[Address]
Address=10.1.2.3/28

[Network]
DNS=10.0.80.11
DNS=10.0.80.12
```

`10_eth0:1.network` is for the virtual interface `eth0:1` but it's not valid. The virtual interface can't use a separate network file. Instead, it should be defined in its physical interface `eth0` network file `10_eth0.network` with `Label` under `[Address]` section. `10_eth0.network` should be like this:
```
# cat 10_eth0.network
# Generated by bosh-agent
[Match]
Name=eth0

[Address]
Address=10.4.5.6/24

[Network]
DNS=10.0.80.11
DNS=10.0.80.12

[Route]
Destination=10.0.0.0/8
Gateway=10.4.5.1

[Route]
Destination=161.26.0.0/16
Gateway=10.4.5.1

[Address]
Label=eth0:1
Address=10.1.2.3/28
```

Note that 
```
[Address]
Label=eth0:1
Address=10.1.2.3/28
```
is appended to `10_eth0.network`

I worked out PR https://github.com/cloudfoundry/bosh-agent/pull/225 which can fix the issue. You can take it as a reference to provide a more elegant fix. Thanks.

**Comment by aashah** [comment]
Hey @gu-bin,

We think we've fixed this through these commits - https://github.com/cloudfoundry/bosh-agent/compare/d3b8e93a014962b55e2bf4b22a74ec3fd9b51e0b...260862064739d9e0bbdb088afcb068fdf21b9d9b

We'll get this work in the 621.x line soon. Thanks for sharing feedback on the new 621.x stemcells and systemd-networkd changes. Please keep it coming!

Aakash
