### ISSUE TITLE
DNS entries from cloud-config are not getting updated correctly post bosh deployment

### ISSUE THREAD

**Issue by pinaki124** [cloudfoundry/bosh-agent#240]
We are experiencing an issue with the DNS configuration in BOSH provisioned VMs. We are deploying to AWS and have 'DNS resolution' enabled by default at the VPC level. We have our own DNS provider running inside this VPC, so as part of our 'network' definition in the cloud-config, we are specifying the DNS entries for our provider. For context, the VPC CIDR is - 10.128.0.0/18, the 'default' VPC DNS nameserver is 10.128.0.2 and the addresses for the DNS provider is 10.128.1.11, 10.128.2.12, 10.129.0.13 - which is what is defined in the cloud config. The stemcell we are using is the most recent version of ubuntu-xenial - https://bosh-aws-light-stemcells.s3-accelerate.amazonaws.com/621.99/light-bosh-stemcell-621.99-aws-xen-hvm-ubuntu-xenial-go_agent.tgz.

The idea of defining the DNS entries in the cloud-config is for the agent to override the default DNS in the VM with the one provided by the cloud-config, but that is not working as expected. Post VM provisioning and update by BOSH, we expect the resolv.conf to have the following entries:

```
nameserver 10.128.1.11
nameserver 10.128.2.12
nameserver 10.129.0.13
search us-west-2.compute.internal
```
but, it has (notice how the AWS default DNS server is on top of the list):

```
nameserver 10.128.0.2
nameserver 10.128.1.11
nameserver 10.128.2.12
search us-west-2.compute.internal
```
This is effecting service discovery for our applications. Now looking through the code, and the agent logs, I can see that the agent calls the 'resolvconf -u' command directly to update the DNS entries, which basically is reading the 'base' file (which is what the agent updates with the DNS entries provided by the user, in the cloud-config) and the 'networkd' file from /run/resolvconf/interface and creating a unique list of 3 entries for the resolv.conf (this is what 'libc' does behind the scenes). I tried running this command with the 'libc' script set in debug mode and its basically what is placing 10.128.0.2 in my case at the top of the list. 

Anyways, digging deeper into the code, I also see the agent updating the 'dhclient.conf' file with the correct entries for DNS and also the '/etc/systemd/network' folder with a network file containing the correct DNS entries. So 2 questions:

1) If the dhclient.conf is being udapted - why is the agent not calling 'dhclient' to update the DNS (which in turn calls 'resolvconf' anyways)? I tried manually executing it in the VM and I got the correct data being fed into the resolv.conf.

2) Instead of updating the 'base' file, should the agent be updating the 'head' file in this scenario (where DNS servers are provided), which would guarantee the entries are added to the top of the file?

I am attaching the agent log for your reference, and also snippets of information about the files in question from the VM:

[bosh-agent-logs-2020-02-01.log](https://github.com/cloudfoundry/bosh-agent/files/5907275/bosh-agent-logs-2020-02-01.log)

```
nginx/7a6c11c1-57dc-4c57-ad7f-0305e9b2c168:/var/vcap/bosh/log# cat /run/resolvconf/interface/networkd 
nameserver 10.128.0.2
nameserver 10.128.1.11 10.128.2.12 10.129.0.13 10.128.0.2
search us-west-2.compute.internal

cat /run/resolvconf/resolv.conf 
nameserver 10.128.0.2
nameserver 10.128.1.11
nameserver 10.128.2.12
search us-west-2.compute.internal

nginx/7a6c11c1-57dc-4c57-ad7f-0305e9b2c168:/var/vcap/bosh/log# ls -l --full-time /run/resolvconf/resolv.conf 
-rw-r--r-- 1 root root 102 2021-02-01 21:24:38.208000000 +0000 /run/resolvconf/resolv.conf
```

**Comment by Justin-W** [comment]
Thanks to @ramonskie for finding this info: https://github.com/cloudfoundry/bosh-agent/pull/277#issuecomment-1102241582
