### ISSUE TITLE
bin/test-bosh-integration dev script is broken

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh-agent#263]
The bin/test-bosh-integration dev script is broken, and fails to clone the https://github.com/cloudfoundry/bosh repo because [the script code](https://github.com/cloudfoundry/bosh-agent/blob/6d105793b00e0d45a2fd4a94419eadaff8322e81/bin/test-bosh-integration#L13-L17) still references that repo's (deleted) https://github.com/cloudfoundry/bosh/tree/master branch, instead of the https://github.com/cloudfoundry/bosh/tree/main branch.

Since the `bin/test-bosh-integration` script is still referenced in the [docs/dev_setup.md](https://github.com/cloudfoundry/bosh-agent/blob/6d105793b00e0d45a2fd4a94419eadaff8322e81/docs/dev_setup.md?plain=1#L90) docs, I would assume it is still supposed to be functional.

However, even after updating the references to the `cloudfoundry/bosh/master` branch to instead use  `cloudfoundry/bosh/main`, the script still fails [here](https://github.com/cloudfoundry/bosh-agent/blob/6d105793b00e0d45a2fd4a94419eadaff8322e81/bin/test-bosh-integration#L24-L25) (though with a different error).

**Comment by Justin-W** [comment]
Also, running the `bin/test-bosh-integration` script creates the `./tmp/bosh/` subdir as a side effect, and the presence of that subdir seems to cause the `bin/test-unit` script to fail until/unless the subdir is manually deleted. That was an unexpected and seemingly undocumented side effect.

Given the number of different errors I encountered while (unsuccessfully) attempting to run the `bin/test-bosh-integration` script, and my uncertainty about whether it is still supposed to be functional (given that it has been broken for a while now), I stopped trying to get it to run at this point.

**Comment by rkoster** [comment]
Which version of ruby did you use?

**Comment by Justin-W** [comment]
> Which version of ruby did you use?

```
bosh-agent % ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [-darwin20]
```

**Comment by rkoster** [comment]
Yeah that could explain why the bundle install failed. The bosh director now uses ruby 3.1
