### ISSUE TITLE
Want to change the password of root and vcap separately

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#28]
The [setUserPasswords](https://github.com/cloudfoundry/bosh-agent/blob/585d2cc3a47129aa875738f09a26101ec6e0b1d1/agent/bootstrap.go#L114) method changes the password of both root and vcap, but we just want to change vcap password or set the different password for vcap and root. Possible to consider to separate this method to 2 method: setUserPasswords and setRootPasswords? Thanks.  @maximilien @jianqiu
```go
func (boot bootstrap) setUserPasswords(env boshsettings.Env) error {
	password := env.GetPassword()
	if password == "" {
		return nil
	}

	err := boot.platform.SetUserPassword(boshsettings.RootUsername, password)
	if err != nil {
		return bosherr.WrapError(err, "Setting root password")
	}

	err = boot.platform.SetUserPassword(boshsettings.VCAPUsername, password)
	if err != nil {
		return bosherr.WrapError(err, "Setting vcap password")
	}

	return nil
}
```

**Comment by maximilien** [comment]
@mattcui do you have (or are working on) PR for this?

**Comment by mattcui** [comment]
@maximilien , haven't, just want to see if they would like to accept this idea before implementation.

**Comment by cppforlife** [comment]
Sure. Let's expose this configuration under env.GetRootPassword() (would read root_password off of the env struct; https://github.com/cloudfoundry/bosh-agent/blob/533ac3615acf55775502238479c2c9dc28e135db/settings/settings.go#L100-L102). If it's not specified in the env use fallback to env.GetPassword().

**Comment by mattcui** [comment]
@cppforlife In generally, we don't change root password, so I think we could make a bit change on your idea, if the root's password is set in env, agent will retrieve and set it as new root password, but if there isn't, agent should not change root's password. How about that? Thanks.

**Comment by maximilien** [comment]
@mattcui this is open for contribution so this means the BOSH team and @cppforlife wants you or anyone to submit a PR and they will consider it.

**Comment by mattcui** [comment]
@maximilien @cppforlife , I already submitted [PR 32](https://github.com/cloudfoundry/bosh-agent/pull/32). Please review. Thanks.

**Comment by cppforlife** [comment]
closing this issue in favor of discussion in pr#32.
