### ISSUE TITLE
[Windows] Failing process not reliably reported

### ISSUE THREAD

**Issue by omergdn** [cloudfoundry/bosh-agent#290]
Opening a new issue as it seems like the original issue won't re-open,

I'm basically experiencing the same exact issue as in https://github.com/cloudfoundry/bosh-agent/issues/219

Environment details:  
Tanzu Ops Manager + BOSH Director version: v2.10.39-build.450
VMware Tanzu Application Service version: v2.11.19
VMware Tanzu Application Service for Windows version: v2.11.11
Windows stemcell version: windows2019 2019.48

Thanks

**Comment by rkoster** [comment]
We currently don't have community resources available to look into this. We happely review a PR addressing this issue. Alternatlify you could raise an issue with VMware since it looks like you are using their commercial distribution of the windows stemcell.
