### ISSUE TITLE
Modify the default setup of connection between agent and nats on director

### ISSUE THREAD

**Issue by Malsourie** [cloudfoundry/bosh-agent#302]
Hi,

Setup: 
we are currently trying to restore the director in different AZ, in which case there will be two directors - the old and the new one. The nats in bosh director manifest is configured as a url, and we create a dns record of it to point to the bosh director ip address. In the restore process we change the record to let it point to the new director. 

Issue:
After we restore the new one, we executed `bosh vms` to check the agents status. Unfortunately all vms are marked as `unresponsive agent`. We checked the heartbeat log on the vms and they are still sending the heartbeats to the old director, although the url is pointed to the new director.

Further we have done some experiments, and it turns out a reconnection between nats on director and agents will only happen if the already existing connection is broken. We have checked the source code, it seems that the nats client is configured as [runUntilInterrupted way](https://github.com/cloudfoundry/bosh-agent/blob/8275a449fc0a25381091dc737f7bdb93d9d6854a/mbus/nats_handler.go#L119). Would it make sense in this case that we add a flag for that [method](https://github.com/cloudfoundry/bosh-agent/blob/main/mbus/nats_handler.go#L269-L280), like `reconnect interval`, to reconnect to the nats in a specific time interval?

Thanks and best regards,
Chun

**Comment by rkoster** [comment]
Should we keep this issue open? or have y'all found a workaround?
