### ISSUE TITLE
bosh-agent kills dhclient 

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-agent#31]
We are working on Azure CPI. And in our stemcell, there is a linux agent which is monitoring dhclient and it will restore the routes if dhcp client is restarted.
https://github.com/Azure/WALinuxAgent/blob/2.0/waagent#L3088

But dhclient is killed by bosh-agent.
https://github.com/cloudfoundry/bosh-agent/blob/master/platform/net/ubuntu_net_manager.go#L140

Any suggestion on this? Thanks in advance.

**Comment by cppforlife** [comment]
On azure, do we always rely on DHCP to configure an IP (i.e. for both manual and dynamic bosh networks)? If so, that's similar to what we do in AWS CPI and we should just set use_dhcp=true always: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/646ae590eff8f0b845f8fb469c9a91826492d62b/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L779

**Comment by cppforlife** [comment]
Btw https://github.com/cloudfoundry/bosh-agent/blob/master/platform/net/ubuntu_net_manager.go#L206 does restart dhclient for each network interface if it is configured to be dhcp.

**Comment by cppforlife** [comment]
@bingosummer @abelhu closing this issue since i think it has been resolved by using use_dhcp=true.
