### ISSUE TITLE
Document compile command on bosh.io

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh-agent#318]
https://github.com/cloudfoundry/bosh-agent/pull/315 added the compile command, but we don't have docs that explain how it can be used.

**Comment by crhntr** [comment]
Would [this document](https://bosh.io/docs/compiled-releases/) be a good spot to PR some documentation?

**Comment by crhntr** [comment]
Can the stemcell container images pull-able from outside the corporate network? Can a open source user build an image?

**Comment by rkoster** [comment]
taking a warden stemcell, untarring it, and running a `docker import` on the image file should work. But I agree ideally we publish stemcell images to an OCI image registry.

**Comment by crhntr** [comment]
The warden stemcell thing sounds like a fun thing to learn anyways. I'll time box figuring that out and documenting it.
