### ISSUE TITLE
Bosh agent blobstore client ignores the configuration in update-settings.json

### ISSUE THREAD

**Issue by Malsourie** [cloudfoundry/bosh-agent#333]
During migration to Azure Storage-Account as external blobstore of bosh director, we faced a certificate issue. We checked the code in bosh-agent and the behaviour of the bosh-agent configuration, and it seems that:
1. if we update the agent blobstore ca in the director manifest and redeploy the deployments without `--recreate` flag, the new ca will be added into `blobstore` config in `update-settings.json` file instead of directly into `settings.json` file.
2. When the blobstore client is being configured, it will ignore the settings in `update-settings.json` and only take the ca from `settings.json`, see: https://github.com/cloudfoundry/bosh-agent/blob/d2bb9fc036e08df95e7a9c4af964793b04907f2a/app/app.go#L173
3. The config in `update-settings.json` will be merged into `settings.json`, if and only if the vm is recreated.

I guess this is the reason whenever we want to migrate to external blobstore or rotate the blobstore ca in agent, we need to recreate the vms. Would it make sense that the blobstore client also takes the config in `update-settings.json` into account?

**Comment by beyhan** [comment]
No `--recreate` should be required. The [documentation](https://bosh.io/docs/blobstore-ca-rotation/) states this also. This is definitely a bug and the change was documented with [this commit](https://github.com/cloudfoundry/docs-bosh/commit/4fed093d5271e64f4d930fa756bde7d4e1d7f297#diff-c022a8f99ef2aec3dc29760626a3961e919e41f947368ef78f59fa6d84818f94).

**Comment by beyhan** [comment]
After discussing this during FI WG today it seems to be a missing feature which was implemented only for the NATs certs.

**Comment by jpalermo** [comment]
Hey @Malsourie, the `blobstoreHTTPClient` gets the config via the settings service: `settingsService.GetSettings().GetBlobstore()`.

But the [settings service](https://github.com/cloudfoundry/bosh-agent/blob/58cdd296386c87dd3b8b074bbe4da0a591d760dc/settings/settings.go#L170-L178) pulls the settings from `update-settings.json` first. So it seems like your rotation should work without recreate.

Could you confirm that the new CA is found inside of `update-settings.json` after a deploy?

**Comment by Malsourie** [comment]
Hey @jpalermo , yes you are totally right. According to the code, the ca should be rendered into the update-settings.json and consumed by the agent. We will do more research about the migration. Thank you for clarifying the procedure!
