### ISSUE TITLE
Possible to enlarge the size of /tmp (/dev/loop0) 

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#34]
Currently, the size of /tmp is 128M, hardcoded in agent code -> https://github.com/cloudfoundry/bosh-agent/blob/56fc289fd7c9fb436d694f6553eed96177efe665/platform/linux_platform.go#L634

```go
	if !systemTmpDirIsMounted {
		// If it's not mounted on /tmp, blow it away
		_, _, _, err = p.cmdRunner.RunCommand("truncate", "-s", "128M", boshRootTmpPath)
		if err != nil {
			return bosherr.WrapError(err, "Truncating root tmp dir")
		}

		_, _, _, err = p.cmdRunner.RunCommand("chmod", "0700", boshRootTmpPath)
		if err != nil {
			return bosherr.WrapError(err, "Chmoding root tmp dir")
		}

		_, _, _, err = p.cmdRunner.RunCommand("mke2fs", "-t", "ext4", "-m", "1", "-F", boshRootTmpPath)
		if err != nil {
			return bosherr.WrapError(err, "Creating root tmp dir filesystem")
		}

		err = p.diskManager.GetMounter().Mount(boshRootTmpPath, systemTmpDir, "-t", "ext4", "-o", "loop")
		if err != nil {
			return bosherr.WrapError(err, "Mounting root tmp dir over /tmp")
		}
```

Some guys raised the request to me to hope to enlarge the size in the stemcell since they want to install some software which need to consume much space in /tmp. Can we consider to parameterize it to be able to specify the size of /tmp in deployment yaml? Thanks.

**Comment by cppforlife** [comment]
This is on purpose. They should set TMPDIR environment variable before executing their software. For example: https://github.com/cloudfoundry/bosh/blob/ede389a2e112e1b4f2dbc4495c08977da4439483/release/jobs/director/templates/scheduler_ctl.erb#L17
