### ISSUE TITLE
Can we close 6868 port due to Poodle Vulnerability problem?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#40]
We got a security warning where 6868 port (used by Bosh Agent in the director VM) is affected by Poodle Vulnerability. So we want to confirm with Bosh community whether this port is still useful after director is deployed. To solve this security issue, we consider to set iptable to block inbound access to this port if it's no use, or is there a better way you guys could advise. Thanks.

CC @maximilien

**Comment by cppforlife** [comment]
Changes were made to bosh-agent some time ago to address this problem: https://github.com/cloudfoundry/bosh-agent/blob/master/httpsdispatcher/https_dispatcher.go (and https://github.com/cloudfoundry/bosh/commit/9ec67d528e051a4ccb4081be2ddb7d60c17d26a7)

I've also checked with `https://github.com/jvehent/cipherscan` to see which protocols are supported and SSLv3 is now shown.

```
$ ./cipherscan my-ip:6868
Warning: target is not a FQDN. SNI was disabled. Use a FQDN or '-servername <fqdn>'
...............
Target: my-ip:6868

prio  ciphersuite                  protocols              pfs                 curves
1     AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
2     AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
3     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
4     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
5     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1

Certificate: untrusted, 2048 bits, sha1WithRSAEncryption signature
TLS ticket lifetime hint: None
OCSP stapling: not supported
Cipher ordering: server
Curves ordering: server - fallback: no
Server supports secure renegotiation
Server supported compression methods: NONE
TLS Tolerance: yes
```

Which stemcell version are you using?

**Comment by mattcui** [comment]
Thank you, we built the stemcell based on a pretty old bosh release, I will merge this change into our code, and rebuild bosh agent.
