### ISSUE TITLE
Commit 1c68a2efd72c3d7504ff8006f7a55e01dee82d5b will lead to the failure of stemcell building

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry/bosh-agent#45]
We happened to see an error which block bosh-agent from launching during the building of stemcells. and this will lead to the failure of building stemcell. we tried to revert two commits of bosh-agent branch and then we can successfully build a stemcell. 

seems the change of commit 1c68a2efd72c3d7504ff8006f7a55e01dee82d5b, around the changes of https://github.com/cloudfoundry/bosh-agent/commit/1c68a2efd72c3d7504ff8006f7a55e01dee82d5b#diff-07cac04980e3140b8f2168929ed868cbL47 
will have some problem like incorrect unmarshal public key, which may lead to the launch failure of bosh-agent. 

Create this issue for further investigation.

IBM pair, Tom and Edward

cc: @cppforlife

**Comment by cppforlife** [comment]
Reopen if this is still a problem.
