### ISSUE TITLE
Question: Does agent support to add non-IP entries in DNS resolver (resolv.conf or interface)

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#50]
We got a requirement to add "options single-request" into DNS resolver, I think user_data.json should be set like below, I don't want agent to add an entry like "nameserver options single-request":

``` json
{"vm":{"name":"vm-24492677-7e7464fe3b"},"agent_id":"24492677-c4cb-43d5-8e4b-a17e7464fe3b","mbus":"nats://nats:nats@10.10.10.9:4222","networks":{"default":{"type":"dynamic","dns":["8.8.8.8","10.100.100.99","10.0.99.99", "options single-request"],"default":["dns","gateway"]}},"blobstore":{"provider":"dav","options":{"endpoint":"http://110.10.10.9:25250","user":"agent","password":"agent"}},"server":{"name":"vm-24492677-7e7464fe3b"},"disks":{"persistent":{}}}
```

I know bosh-agent overwrites DNS resolver file during agent start. Is there any other condition to have agent overwrite DNS resolver? Thanks.

**Comment by cppforlife** [comment]
dns key is designed to set dns nameservers, nothing else. configuring dns options should be its own configuration. while we dont support this right now (we'll think more about how to configure it) you can create a release that changes /etc/resolvconf/resolv.conf.d/tail and adds appropriate options.

**Comment by mattcui** [comment]
The problem is that bosh-agent will overwrite resolver file when it's restarted, all added options will be purged.

**Comment by bosh-ci-push-pull** [comment]
That's why I'm suggesting to place it into
/etc/resolvconf/resolv.conf.d/tail instead of /etc/resolv.conf so that
resolvconf -u picks this up.

**Comment by mattcui** [comment]
but maybe the agent is restarted by accident or someone manually (not during system boot) sometimes, we can't guarantee resolv.conf includes entries from /etc/resolvconf/resolv.conf.d/tail at all time.

**Comment by bosh-ci-push-pull** [comment]
/tail in resolvconf.d is a correct place to put additional info. bosh-agent
(and/or os script) when reconfiguring network will call resolvconf -u (
https://github.com/cloudfoundry/bosh-agent/blob/master/platform/net/ubuntu_net_manager.go#L379)
which will properly account for /tail.

**Comment by tylerschultz** [comment]
Closing per the suggestion to use a release that edits /etc/resolvconf/resolv.conf.d/tail. Re-open if you think there is more to discuss. Thanks.
