### ISSUE TITLE
Proposal: http registry client basic auth

### ISSUE THREAD

**Issue by uzzz** [cloudfoundry/bosh-agent#55]
What do you think about passing http basic auth username & password for registry along with the endpoint via metadata service (and using it later in httpRegistry to authenticate requests)? It would allow to avoid IaaS-specific code in bosh-registry (https://github.com/cloudfoundry/bosh/tree/master/bosh-registry/lib/bosh/registry/instance_manager, instance_ips method) which is useful when adopting bosh to a new IaaSes.

**Comment by cppforlife** [comment]
That's already an option. We did that for Azure support so that we didn't have to add Azure specific code to the registry (while registry is still here). Docs: http://bosh.io/docs/openstack-registry.html

**Comment by uzzz** [comment]
Great, just tried – it works. Thank you. Closing issue.
