### ISSUE TITLE
bosh-agent ignores use_dhcp setting when attach multiple networks

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry/bosh-agent#64]
I'm using bosh-openstack-kvm-ubuntu-trusty-go_agent v3181 on OpenStack.
So, attach multiple networks to vm with ```use_dhcp: false``` option but can not disable DHCP. 

Following is bosh-agent's log.
You can see two networks attached and each network is disabled DHCP.
![fig1](https://cloud.githubusercontent.com/assets/1715090/12577172/0c3ab34e-c45c-11e5-9fee-c8e8edb30003.jpg)

But bosh-init uses ```dhcp networking``` mode because does not extract network settings.
![fig2](https://cloud.githubusercontent.com/assets/1715090/12577175/11914164-c45c-11e5-86a1-52f0c925c927.jpg)

p.s.
Work correctly when attach only one network.

**Comment by kei-yamazaki** [comment]
I found following code in [interface_configuration_creator.go#L133-L139](https://github.com/cloudfoundry/bosh-agent/blob/0ea9fff9f49552de27f9d003497c947e65a71bd8/platform/net/interface_configuration_creator.go#L133-L139).
```go
for mac, ifaceName := range interfacesByMAC {
	networkSettings, _ = networks.NetworkForMac(mac)
	staticConfigs, dhcpConfigs, err = creator.createInterfaceConfiguration(staticConfigs, dhcpConfigs, ifaceName, networkSettings)
	if err != nil {
		return nil, nil, bosherr.WrapError(err, "Creating interface configuration")
	}
}
```

This code get each interface's network settings with `networks.NetworkForMac(mac)`, but `networks.NetworkForMac(mac)` alway returns empty network settings because `networks` is not set mac address here.

So `interface_configuration_creator` uses DHCP networking mode with [this condition](https://github.com/cloudfoundry/bosh-agent/blob/0ea9fff9f49552de27f9d003497c947e65a71bd8/platform/net/interface_configuration_creator.go#L72).

I tried to fix this problem but can not because network name (e.g. cf1, cf2. not interface name) does not relate to mac address.

**Comment by cppforlife** [comment]
cc @voelzmo

**Comment by cppforlife** [comment]
I believe OpenStack CPI currently does not set MAC addresses on networks which makes agent fall back to DHCP. Until it starts including MAC addresses agent would not be able to determine which static configuration to apply to which network.

**Comment by voelzmo** [comment]
We can investigate to add support for multiple manual networks on a single VM without DHCP to the OpenStack CPI. Out of curiosity: Does your OpenStack not offer DHCP or do you not want to use it due to another reason?

**Comment by kei-yamazaki** [comment]
@cppforlife 

OpenStack CPI currently does not set MAC addresses.
It should set MAC addresses when creating ports.

BTW, does other CPI set MAC addresses when creating multiple networks?

@voelzmo 

It's technical reason.
Our OpenStack does not offer DHCP on some network.
In general, most network offers DHCP.

**Comment by voelzmo** [comment]
@kei-yamazaki The vSphere cpi sets mac addresses, because it doesn't support DHCP. Thanks for the explanations, I filed a story in our backlog: https://www.pivotaltracker.com/story/show/112755661

**Comment by voelzmo** [comment]
@kei-yamazaki we have released [v24](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/releases/tag/v24) of the OpenStack CPI including support for multiple networks with DHCP disabled. Please note that when using multiple networks, you cannot use DHCP for any of the networks for now.

**Comment by kei-yamazaki** [comment]
@voelzmo I'll try. Thanks!
