### ISSUE TITLE
bosh agent doesn't clean /var/vcap/data/root_tmp when upgrade from old stemcell

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-agent#83]
This problem should only happen in Softlayer as we do os-reload to upgrade stemcell. We open this issue to see if community can help solve it. Thanks.

We are trying to upgrade stemcell from 3169 to 3262.2. During the upgrade, the vm bosh agent failed to start due to 

```
2016-07-21_06:55:19.43133 [main] 2016/07/21 06:55:19 ERROR - App setup Running bootstrap: Setting up tmp dir: Creating root tmp dir: Running command: 'mkdir -p /var/vcap/data/root_tmp', stdout: '', stderr: 'mkdir: cannot create directory '/var/vcap/data/root_tmp': File exists
```

This is because in old stemcell 3169, /var/vcap/data/root_tmp exists in the ephemeral disk like this:

```
-rwx------ 1 root root 134217728 Jul 21 08:38 /var/vcap/data/root_tmp*
```

During stemcell upgrade, we do os-reload in Softlayer and keep using the existing ephemeral disk. So the file /var/vcap/data/root_tmp is still there.

But in new stemcell 3262.2, bosh agent changes to create a directory with the same name at the same place. As the ephemeral disk is not recreated, bosh agent handles it as an existing one and doesn't clean it. As a result, bosh agent failed to create the directory /var/vcap/data/root_tmp and fail to start.

If possible, would you please fix it like this:
Before run `mkdir -p /var/vcap/data/root_tmp`, check if there is a file with the same name and path existing. If yes, remove it. Thanks.

/cc @maximilien @jianqiu @mattcui

**Comment by maximilien** [comment]
Should be a straight forward change to `linux_platform.go` in [lines 700-703](https://github.com/cloudfoundry/bosh-agent/blob/8a1a382bf63892f833935c1cf79afc4bdd3fb78b/platform/linux_platform.go#L700-L703)

from

```
err := p.fs.MkdirAll(boshTmpDir, tmpDirPermissions)
if err != nil {
	return bosherr.WrapError(err, "Creating temp dir")
}
```

to something like

```
_, err := os.Stat(boshTmpDir)
if !os.IsNotExist(err) {
  err = os.RemoveAll(boshTmpDir)
  if err != nil {
	  return bosherr.WrapError(err, "Removing temp dir")
  }
}

err := p.fs.MkdirAll(boshTmpDir, tmpDirPermissions)
if err != nil {
	return bosherr.WrapError(err, "Creating temp dir")
}
```

With appropriate tests (of course)

@cppforlife what do you think? Shall we submit a PR?

**Comment by cppforlife** [comment]
MkdirAll already checks if directory is present.

Agent is not meant to run against a system that has been previously bootstrapped by the older agent.

My suggestion while doing OS reload, you should get a new ephemeral disk and attach it to the VM.

**Comment by jianqiu** [comment]
@cppforlife @maximilien @mattcui 
It makes sense to us that agent is not meant to run against an existing ephemeral disk, but there is a limit to remove ephemeral disk in SL, removing ephemeral disk from SL infrastructure should open a ticket to SL support firstly, that means the disk could not be deleted immediately, and it is hard to get a new ephemeral disk.

**Comment by cppforlife** [comment]
@jianqiu isnt it part of standard vm provisioning workflow? how do open source users of softlayer cpis get their vms with ephemeral disks?

**Comment by gu-bin** [comment]
@cppforlife ephemeral disks creation and modification can be done via API immediately. But deleting ephemeral disks need to open a ticket to SL support firstly, and then need to wait some time before they are finally deleted. So it's hard for CPI to handle.

Currently we have 2 workarounds:
1. Set ``"UseDefaultTmpDir": true`` in ``user_data.json`` to avoid ``mkdir -p /var/vcap/data/root_tmp``
2. In our CPI code, clean the ephemeral disk first after attaching it

**Comment by mattcui** [comment]
@maximilien A side effect of option #2 is that eCPI has to login target VMs via SSH to handle it. But one of our goal is to get rid of all ssh connection from eCPI to target VMs, then we can disable root remote login in stemcell in future.

**Comment by maximilien** [comment]
OK thanks @mattcui. What are the consequences of option 1?

**Comment by gu-bin** [comment]
@maximilien Option 1 will make ``/tmp`` use the same disk partition as ``/`` rather than use the separated partition (with limited size) that mounted to ``/var/vcap/data``. This option can fix the problem and ``/tmp`` can use larger size. The disadvantage is that ``/tmp`` is not isolated from ``/`` and maybe become too large which will affect the system.
/cc @mattcui @jianqiu

**Comment by maximilien** [comment]
OK, so @cppforlife and I chatted about this today. We have a proposal he seems happy with that should work for us. Let me try to capture the details in a short write up and post here. I'll do this by EOD. Likely tonight.

Cheers all.

**Comment by cppforlife** [comment]
Proposed solution:

- Agent can record agent version onto ephemeral disk (/var/vcap/data/.bosh/agent_version)
- Next time agent restarts as part of LinuxPlatform#SetupEphemeralDiskWithPath check if that file contains a different version
- If version is same, don't do anything
- If version is different, rm -rf all contents in /var/vcap/data/* and write a new version

Let's add a new option to the agent (https://github.com/cloudfoundry/bosh-agent/blob/master/platform/linux_platform.go#L47) to enable this behavior -- ScrubEphemeralDisk (bool).

**Comment by maximilien** [comment]
@gu-bin @jianqiu and @mattcui let me know if you need help. Let's work on a PR. Thx.

**Comment by zhanggbj** [comment]
Hi @cppforlife , @maximilien 
We would like to submit a PR, but I have some questions about the solution, that is,

1. Is there somewhere that records `agent version`? or we should use `/var/vcap/bosh/etc/stemcell_version` as `/var/vcap/data/.bosh/agent_version`?

2. To update properties in the resource pool will also trigger os-reload. However in this situation, we are using the same stemcell but need to scrub the ephemeral disk. It seems that this case is not covered currently. 

Thank you!

**Comment by cppforlife** [comment]
1. stemcell version is fine.
2. you wouldnt need to clean up if it's the same stemcell, since same stemcell means same agent.
