### ISSUE TITLE
Allow to configure logrotate frequency

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh-agent#84]
Currently logrotate is hardcoded to run every hour. For some jobs that are generating lots of logs we would like to be able to increase the frequency at which logrotate runs.

**Comment by cppforlife** [comment]
@CAFxX we've actually increased freq to every 15 mins on develop to be more aggressive. i imagine though that you are proposing to make it more flexible. who do you think should be responsible for setting log rotation frequency? operator vs release author vs both.

**Comment by CAFxX** [comment]
At the very least operator. If there was a way for the release author to give a sensible default it would be even better (although I would be plenty happy even just with just the operator)

**Comment by cppforlife** [comment]
@CAFxX out of curiosity what are typically the values you would be setting for logrotate for your deployment size?

**Comment by CAFxX** [comment]
Our primary use-case would be on our Kafka cluster. Kafka can be incredibly chatty in its logs during partition reassignment (e.g. every time a node is shutdown for bosh deploy, or when a node crashes).
While most of the time it wouldn't be required, when such an event takes place I'd say that we need to logrotate every 5 minutes.

**Comment by cppforlife** [comment]
@CAFxX btw we now bind mount /var/logs to ephemeral disk in 3262.9 stemcell. do you think increasing ephemeral disk size to account for kafka activity is ok?

**Comment by CAFxX** [comment]
@cppforlife I don't think that will be much of a difference in our case, we run on-premises.

**Comment by dpb587-pivotal** [comment]
Closing - recent stemcells logrotate every 15m and immediately compress the files which has led to significantly reduced log disk usage in our deployments. If you're still experiencing issues, please feel free to reply to this issue to reopen for discussion.
