### ISSUE TITLE
Disk percentage metrics are 5% off

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/bosh-agent#89]
It seems that Disk metrics reported by BOSH and the values that are observed on the VMs don't match. The most promimant difference is in the free disk percentage.

After some investigation, the problem was narrowed down to BOSH not taking into account the reserved disk space on the volume.

> **-m reserved-blocks-percentage**
> Set the percentage of the filesystem which may only be allocated by privileged processes. Reserving some number of filesystem blocks for use by privileged processes is done to avoid filesystem fragmentation, and to allow system daemons, such as syslogd(8), to continue to function correctly after non-privileged processes are prevented from writing to the filesystem. Normally, the default percentage of reserved blocks is 5%.
> http://linux.die.net/man/8/tune2fs

You can further check that by running `df -h` on a machine. You will see that the sum of `Used` and `Avail` comes short of `Size`. That's because the `Free` value shows only what is available to a non-root user (i.e. does not include reserved disk). The reported percentage, however, takes reserved disk space into account and reports the correct value for a non-root user.

The problem is that BOSH reports the disk that is available to the root user and BOSH releases use the `vcap` user to run jobs. This means that when BOSH reports `95%` usage, the job has actually consumed `100%` of the disk and is crashing, something the operator might not be aware of.

Fixing this would require a change to [sigar_stats_collector](https://github.com/cloudfoundry/bosh-agent/blob/master/sigar/sigar_stats_collector.go).

One way to solve this would be to correct the `Total` metric, taking reserved space into account.

``` go
func (s *sigarStatsCollector) GetDiskStats(mountedPath string) (stats boshstats.DiskStats, err error) {
    fsUsage, err := s.statsSigar.GetFileSystemUsage(mountedPath)
    if err != nil {
        err = bosherr.WrapError(err, "Getting Sigar File System Usage")
        return
    }

        // Free is the disk available to root (includes reserved)
        // Avail is the disk available to non-root
    reserved := fsUsage.Free - fsUsage.Avail
    stats.DiskUsage.Total = fsUsage.Total - reserved
    stats.DiskUsage.Used = fsUsage.Used
    stats.InodeUsage.Total = fsUsage.Files
    stats.InodeUsage.Used = fsUsage.Files - fsUsage.FreeFiles

    return
}
```

Another way would be to report metrics similar to the `df -h` command. This would require a fix to the reported percentage, which should be calculated as follows.

``` go
stats.DiskUsage.Percent = fsUsage.Used / (fsUsage.Total - reserved)
```

This requires a change to the `DiskUsage` struct and more but the idea I guess is clear.

**Comment by cppforlife** [comment]
@momchil-sap nice find! would you like to make a PR?

**Comment by momchil-sap** [comment]
@cppforlife , I wanted to get your opinion first, especially on which approach to take.

As far as I understand it, bosh-agent is only reporting the percentage at the moment, in which case, the solution @ivan-sap has linked should be sufficient. If however, at some point the Total disk is reported, it will be equal to only what is visible to the `vcap` user and not to `root` making it different from the behavior of the `df` tool.

Though the change fixes the percentage for the `vcap` user and aligns at least that aspect to the `df` tool, it could also be misleading for releases that make use of the `root` user. 

Finally, making such a change would be breaking for any alert thresholds that any developers/operators might have set. I guess this would need to be clearly stated in the release notes of the next stemcell.

**Comment by CAFxX** [comment]
On a related but separate issue, while superuser reservation may make sense on the root filesystem, they are probably not needed on persistent disks (especially since persistent disks can become quite large)
